import Head from 'next/head';
import Home from '../components/Home';

import MainLayout from '../layouts/MainLayout';
import { NextPageWithLayout } from '../types/types';

const Index: NextPageWithLayout = () => (
  <>
    <Head>
      <title>nextJs Boilerplate - Page Home</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Home />
  </>
);

export default Index;

Index.getLayout = function getLayout(page: React.ReactElement) {
  return <MainLayout>{page}</MainLayout>;
};
