import Head from 'next/head';
import { useRouter } from 'next/router';
import PostDetails from '../../components/PostDetails';
import MainLayout from '../../layouts/MainLayout';

const Post = () => {
  const router = useRouter();
  const { pid } = router.query;

  return (
    <>
      <Head>
        <title>nextJs Boilerplate - Page Post</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PostDetails pid={pid} />
    </>
  );
};

export default Post;

Post.getLayout = function getLayout(page: React.ReactElement) {
  return <MainLayout>{page}</MainLayout>;
};
